/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int sub_180001000();
struct IAdvancedHookV *CreateAdvHookService(void); // idb
char __fastcall InitFunc(__int64 a1, __int64 a2);
__int64 func2();
__int64 __fastcall func3(__int64 a1, unsigned int *a2, __int64 a3, __int64 a4, int a5, unsigned __int8 a6);
BOOL __fastcall func4(__int64 a1, char a2); // idb
char *callsomefuncs();
char *__fastcall GetHook(__int64 a1);
void __fastcall sub_180001610(void **a1);
char *__fastcall sub_1800016A0(__int64 *a1, unsigned __int8 *a2);
char *__fastcall sub_1800017E0(__int64 a1, size_t a2);
_QWORD *__fastcall sub_180001900(__int64 a1, size_t a2);
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
void *sub_180001980();
_QWORD *__fastcall sub_180001990(_QWORD *a1, __int64 a2);
const char *__fastcall sub_1800019D0(__int64 a1);
void *__fastcall sub_1800019F0(void *Memory, char a2);
__int64 __fastcall sub_180001A40(_QWORD *a1);
void __fastcall sub_180001A60(__int64 a1);
__int64 __fastcall sub_180001AA0(__int64 a1);
void WriteToLog1(__int64 a1, __int64 a2, ...);
void __fastcall sub_180001C10(_QWORD *a1);
__int64 __fastcall sub_180001CB0(__int64 a1);
_QWORD *__fastcall sub_180001D80(_QWORD *a1);
char __fastcall sub_180001E90(__int64 a1, __int64 a2);
signed __int64 __fastcall sub_180001EE0(_QWORD *a1);
__int64 __fastcall sub_180001F30(__int64 a1, char *a2, size_t a3);
_QWORD *__fastcall sub_180001F90(__int64 a1, _QWORD *a2, __int64 *a3);
_QWORD *__fastcall sub_180002080(__int64 a1, _QWORD *a2, __int64 a3, int a4);
signed __int64 __fastcall sub_180002190(__int64 a1);
signed __int64 __fastcall sub_1800024D0(__int64 a1);
signed __int64 __fastcall sub_180002540(__int64 a1, unsigned int a2);
signed __int64 __fastcall sub_180002620(__int64 a1, unsigned int a2);
void __fastcall sub_1800028E0(__int64 a1);
void __fastcall sub_180002900(__int64 a1);
__int64 __fastcall sub_180002920(_QWORD *a1);
char *__fastcall sub_1800029A0(__int64 a1, char a2);
_QWORD **__fastcall sub_180002A00(void *Memory, char a2);
_QWORD *__fastcall sub_180002AA0(_QWORD *a1, unsigned __int64 a2, char a3);
// __int64 __fastcall std::basic_filebuf<char,std::char_traits<char>>::_Reset_back(_QWORD); weak
// __int64 sub_180002BF0(void); weak
__int64 __fastcall sub_180002DD0(__int64 a1, __int64 a2, int a3);
__int64 __fastcall sub_180002E90(__int64 a1);
__int64 __fastcall sub_180002F10(__int64 a1, const char *a2);
char *__fastcall sub_180002FE0(void *Src, signed __int64 a2, size_t a3);
// __int64 __fastcall WriteToLog(_QWORD, _QWORD); weak
// __int64 __fastcall sub_180003380(_QWORD); weak
_QWORD *__fastcall sub_1800034B0(_QWORD *a1, __int64 a2);
__int64 __fastcall sub_1800034F0(__int64 **a1);
__int64 __fastcall sub_180003540(__int64 **a1);
char *__fastcall sub_180003574(__int64 a1, char a2);
// void *__fastcall operator new(size_t Size); idb
_QWORD *__fastcall sub_1800035F0(_QWORD *a1, char a2);
void __cdecl j_free(void *Memory);
void __cdecl j_j_free(void *Memory);
void *__fastcall operator new(size_t Size); // idb
_QWORD *__fastcall sub_180003B4C(_QWORD *a1, __int64 a2);
_QWORD *__fastcall sub_180003B8C(_QWORD *a1);
_QWORD *__fastcall sub_180003BAC(_QWORD *a1, __int64 a2);
_QWORD *__fastcall sub_180003BEC(_QWORD *a1);
// int __cdecl atexit(void (__cdecl *)());
void sub_180004118();
void __cdecl sub_180004128(); // idb
void *sub_180004134();
void *sub_180004158();
__int64 sub_1800042A8();
void __cdecl sub_1800042F4(); // idb
void j___guard_check_icall_fptr();
void nullsub_1();
// __int64 __fastcall _std_exception_copy(_QWORD); weak
// __int64 __fastcall _std_type_info_destroy_list(_QWORD); weak
// void *__cdecl memset(void *Dst, int Val, size_t Size);
char sub_180004680();
__int64 sub_180004684();
// void *__cdecl memcpy(void *Dst, const void *Src, size_t Size);
// __int64 __usercall sub_1800047B0@<rax>(__int64 (*a1)(void)@<rax>);
__int64 sub_1800048CD(void); // weak
// void __usercall sub_1800048FD(__int64 a1@<rbp>);
// __int64 __fastcall unknown_libname_5(); weak
// BOOL __stdcall VirtualProtect(LPVOID lpAddress, SIZE_T dwSize, DWORD flNewProtect, PDWORD lpflOldProtect);
// HANDLE __stdcall GetCurrentProcess();
// BOOL __stdcall K32GetModuleInformation(HANDLE hProcess, HMODULE hModule, LPMODULEINFO lpmodinfo, DWORD cb);
// HMODULE __stdcall GetModuleHandleW(LPCWSTR lpModuleName);
// void __stdcall InitializeSListHead(PSLIST_HEADER ListHead);
// __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::basic_streambuf<char,std::char_traits<char>>(_QWORD); weak
// __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::getloc(_QWORD, _QWORD); weak
// __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::_Init(_QWORD); weak
// __int64 __fastcall std::basic_ios<char,std::char_traits<char>>::setstate(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall std::basic_ios<char,std::char_traits<char>>::basic_ios<char,std::char_traits<char>>(_QWORD); weak
// __int64 __fastcall std::basic_ostream<char,std::char_traits<char>>::basic_ostream<char,std::char_traits<char>>(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall std::basic_ostream<char,std::char_traits<char>>::_Osfx(_QWORD); weak
// __int64 __fastcall std::codecvt<char,char,_Mbstatet>::out(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall std::basic_ios<char,std::char_traits<char>>::~basic_ios<char,std::char_traits<char>>(_QWORD); weak
// __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::~basic_streambuf<char,std::char_traits<char>>(_QWORD); weak
// __int64 __fastcall std::basic_ostream<char,std::char_traits<char>>::~basic_ostream<char,std::char_traits<char>>(_QWORD); weak
// bool std::codecvt_base::always_noconv(std::codecvt_base *__hidden this); weak
// void std::_Xbad_alloc(void); weak
// void __stdcall std::_Xlength_error(const char *); weak
// bool std::uncaught_exception(void); weak
// struct _iobuf *__stdcall std::_Fiopen(const char *, _DWORD, _DWORD); weak
// __int64 __fastcall std::codecvt<char,char,_Mbstatet>::in(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall __std_exception_copy(_QWORD); weak
// __int64 __fastcall __std_exception_destroy(_QWORD); weak
// void *__cdecl memmove(void *Dst, const void *Src, size_t Size);
// int __cdecl strtol(const char *Str, char **EndPtr, int Radix);
// void __cdecl unlock_file(FILE *File);
// void __cdecl lock_file(FILE *File);
// void __cdecl invalid_parameter_noinfo();
// void __cdecl __noreturn invalid_parameter_noinfo_noreturn();
// int *__cdecl errno();
// int __cdecl fgetpos(FILE *File, fpos_t *Pos);
// int __cdecl ungetc(int Ch, FILE *File);
// size_t __cdecl fwrite(const void *Str, size_t Size, size_t Count, FILE *File);
// int __cdecl fsetpos(FILE *File, const fpos_t *Pos);
// __int64 __fastcall get_stream_buffer_pointers(_QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall _stdio_common_vsnprintf_s(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// int __cdecl fseeki64(FILE *File, __int64 Offset, int Origin);
// int __cdecl fgetc(FILE *File);
// int __cdecl fclose(FILE *File);
// int __cdecl fflush(FILE *File);
// int __cdecl fputc(int Ch, FILE *File);
// int __cdecl setvbuf(FILE *File, char *Buf, int Mode, size_t Size);
// errno_t __cdecl strcpy_s(char *Dst, rsize_t SizeInBytes, const char *Src);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_180004932; // weak
_UNKNOWN loc_180004962; // weak
_UNKNOWN loc_180004967; // weak
// extern const __int64 std::_BADOFF; weak
void *type_info::`vftable' = &sub_1800035F0; // weak
void *std::exception::`vftable' = &sub_1800019F0; // weak
void *std::bad_alloc::`vftable' = &unknown_libname_3; // weak
void *std::bad_array_new_length::`vftable' = &unknown_libname_3; // weak
void *Functions::`vftable' = &InitFunc; // weak
void *std::basic_filebuf<char,std::char_traits<char>>::`vftable' = &sub_180002A00; // weak
void *std::basic_ofstream<char,std::char_traits<char>>::`vftable' = &sub_180003574; // weak
void *std::bad_cast::`vftable' = &sub_1800019F0; // weak
_UNKNOWN unk_1800056A0; // weak
_UNKNOWN unk_180006438; // weak
_UNKNOWN unk_180006448; // weak
_UNKNOWN unk_1800088E0; // weak
_UNKNOWN unk_1800088F0; // weak
__int64 test2; // weak
LPVOID lpAddress; // idb
__int64 test1; // weak
__int64 qword_180008928; // weak
char byte_180008930; // weak
__int64 qword_180008938; // weak
HMODULE hModule; // idb
__int64 qword_180008950; // weak
_UNKNOWN unk_180008958; // weak
_UNKNOWN unk_180008960; // weak


//----- (0000000180001000) ----------------------------------------------------
int sub_180001000()
{
  return atexit(unknown_libname_5);
}
// 180004A84: using guessed type __int64 __fastcall unknown_libname_5();

//----- (0000000180001010) ----------------------------------------------------
struct IAdvancedHookV *CreateAdvHookService(void)
{
  struct IAdvancedHookV *result; // rax

  result = operator new(8ui64);
  *result = &Functions::`vftable';
  return result;
}
// 1800054C0: using guessed type void *Functions::`vftable';

//----- (0000000180001030) ----------------------------------------------------
char __fastcall InitFunc(__int64 a1, __int64 a2)
{
  __int64 v2; // rbx

  v2 = a2;
  if ( !byte_180008930 )
  {
    qword_180008928 = operator new(0x12ui64);
    strcpy_s(qword_180008928, 0x12ui64, "AdvancedHookV.log");
    callsomefuncs();
    WriteToLog1(0i64, "AdvancedHookV 0.1 by LMS");
    WriteToLog1(0i64, "Base: 0x%I64X -- Size: 0x%I64X", hModule, qword_180008938);
    byte_180008930 = 1;
  }
  WriteToLog1(0i64, "Service requested from %s", v2);
  return 1;
}
// 180008928: using guessed type __int64 qword_180008928;
// 180008930: using guessed type char byte_180008930;
// 180008938: using guessed type __int64 qword_180008938;

//----- (00000001800010C0) ----------------------------------------------------
__int64 func2()
{
  return byte_180008930;
}
// 180008930: using guessed type char byte_180008930;

//----- (00000001800010D0) ----------------------------------------------------
__int64 __fastcall func3(__int64 a1, unsigned int *a2, __int64 a3, __int64 a4, int a5, unsigned __int8 a6)
{
  unsigned int v6; // xmm0_4
  char *result1; // rbx
  unsigned int v8; // xmm1_4
  unsigned int v9; // edi
  signed __int64 v10; // rcx
  char *result2; // rax
  unsigned __int64 v13; // [rsp+60h] [rbp-58h]
  __int64 v14; // [rsp+68h] [rbp-50h]
  __int64 v15; // [rsp+70h] [rbp-48h]
  __int64 v16; // [rsp+78h] [rbp-40h]

  v6 = *a2;
  result1 = test1;
  v8 = a2[1];
  v9 = a3;
  v14 = 0i64;
  v13 = __PAIR__(v8, v6);
  v14 = a2[2];
  v15 = 0i64;
  v16 = 0i64;
  if ( !test1 )
  {
    result1 = GetHook("44 89 4C 24 20 48 83 EC  28 0F 29 74 24 10 0F 57 C0");
    test1 = result1;
  }
  v10 = test2;
  if ( !test2 )
  {
    result2 = GetHook("F3 0F 11 4C 24 40 F3 0F 11 7C 24 38 0F 28 D3 48 89 44 24 30 44 0B C9");
    v10 = &result2[*(result2 + 26) + 30];
    test2 = &result2[*(result2 + 26) + 30];
  }
  return (result1)(v10, &v13, a3, v9, a5, 1045220557, &v15, 1065353216, 0, 1119092736, a6);
}
// 180008910: using guessed type __int64 test2;
// 180008920: using guessed type __int64 test1;

//----- (0000000180001220) ----------------------------------------------------
BOOL __fastcall func4(__int64 a1, char a2)
{
  _WORD *v2; // rbx
  char v3; // di
  char *v4; // rax
  DWORD flOldProtect; // [rsp+20h] [rbp-18h]

  v2 = lpAddress;
  v3 = a2;
  if ( !lpAddress )
  {
    v4 = GetHook("48 8B 03 45 33 C0 B2 01 48 8B CB FF 90 ?? 05 00 00 48 8B 4B 20");
    v2 = v4 + 11;
    lpAddress = v4 + 11;
  }
  VirtualProtect(v2, 0xFFui64, 0x40u, &flOldProtect);
  if ( v3 )
  {
    *v2 = 96506111;
    v2[2] = 0;
  }
  else
  {
    *v2 = -1869574000;
    v2[2] = -28528;
  }
  return VirtualProtect(v2, 0xFFui64, flOldProtect, &flOldProtect);
}

//----- (00000001800012D0) ----------------------------------------------------
char *callsomefuncs()
{
  HANDLE v0; // rax
  char *result; // rax
  char *v2; // rax
  struct _MODULEINFO modinfo; // [rsp+20h] [rbp-28h]

  hModule = GetModuleHandleW(0i64);
  v0 = GetCurrentProcess();
  K32GetModuleInformation(v0, hModule, &modinfo, 0x18u);
  result = modinfo.SizeOfImage;
  qword_180008938 = modinfo.SizeOfImage;
  if ( !test1 )
  {
    result = GetHook("44 89 4C 24 20 48 83 EC  28 0F 29 74 24 10 0F 57 C0");
    test1 = result;
  }
  if ( !test2 )
  {
    v2 = GetHook("F3 0F 11 4C 24 40 F3 0F 11 7C 24 38 0F 28 D3 48 89 44 24 30 44 0B C9");
    result = &v2[*(v2 + 26) + 30];
    test2 = result;
  }
  if ( !lpAddress )
  {
    result = GetHook("48 8B 03 45 33 C0 B2 01 48 8B CB FF 90 ?? 05 00 00 48 8B 4B 20") + 11;
    lpAddress = result;
  }
  return result;
}
// 180008910: using guessed type __int64 test2;
// 180008920: using guessed type __int64 test1;
// 180008938: using guessed type __int64 qword_180008938;

//----- (00000001800013A0) ----------------------------------------------------
char *__fastcall GetHook(__int64 a1)
{
  __int64 a1_1; // rdi
  char *v2; // r12
  __int64 v3; // r14
  unsigned __int64 v4; // rbx
  signed __int64 v5; // rax
  char v6; // al
  unsigned __int64 v7; // rax
  unsigned int v8; // er11
  char *v9; // rbx
  void *v10; // r9
  char *v11; // r8
  _BYTE *v12; // rcx
  char v13; // dl
  void *v14; // rax
  unsigned __int64 v15; // r14
  char *v16; // rax
  unsigned __int64 v17; // rbx
  char v19; // [rsp+20h] [rbp-50h]
  __int64 v20; // [rsp+28h] [rbp-48h]
  char Str[2]; // [rsp+30h] [rbp-40h]
  char v22; // [rsp+32h] [rbp-3Eh]
  void *Memory[2]; // [rsp+38h] [rbp-38h]
  __int64 v24; // [rsp+48h] [rbp-28h]
  void *v25[2]; // [rsp+50h] [rbp-20h]
  __int64 v26; // [rsp+60h] [rbp-10h]

  v20 = -2i64;
  a1_1 = a1;
  _mm_storeu_si128(v25, 0i64);
  v2 = 0i64;
  v3 = 0i64;
  v26 = 0i64;
  _mm_storeu_si128(Memory, 0i64);
  v24 = 0i64;
  *Str = 0;
  v22 = 0;
  v4 = 0i64;
  v5 = -1i64;
  do
    ++v5;
  while ( *(a1 + v5) );                         // while next is avalible
  if ( !v5 )
    goto not_avalible;
  do
  {
    v6 = *(v4 + a1_1);
    if ( v6 == 63 )
    {
      v19 = 0;
      sub_1800016A0(v25, &v19);
      v19 = 63;
LABEL_8:
      sub_1800016A0(Memory, &v19);
      ++v4;
      goto LABEL_9;
    }
    if ( v6 != 32 )
    {
      Str[0] = *(v4 + a1_1);
      Str[1] = *(v4 + a1_1 + 1);
      v19 = strtol(Str, 0i64, 16);
      sub_1800016A0(v25, &v19);
      v19 = 120;
      goto LABEL_8;
    }
LABEL_9:
    ++v4;
    v7 = -1i64;
    do
      ++v7;
    while ( *(a1_1 + v7) );
  }
  while ( v4 < v7 );
  v3 = v26;
not_avalible:
  v19 = 0;
  sub_1800016A0(Memory, &v19);
  v8 = 0;
  v9 = v25[0];
  v10 = Memory[0];
  if ( !qword_180008938 )
    goto catch_error;
  while ( 2 )
  {
    v11 = Memory[0];
    v12 = v25[0];
    if ( *Memory[0] )
    {
      v13 = *Memory[0];
      while ( v13 != 120 || v12[hModule + v8 - v25[0]] == *v12 )
      {
        ++v11;
        ++v12;
        v13 = *v11;
        if ( !*v11 )
          goto LABEL_19;
      }
LABEL_20:
      if ( ++v8 >= qword_180008938 )
        goto catch_error;
      continue;
    }
    break;
  }
LABEL_19:
  if ( *v11 )
    goto LABEL_20;
  v2 = hModule + v8;
catch_error:
  if ( Memory[0] )
  {
    if ( v24 - Memory[0] > 0xFFFFFFFFFFFFFFFFui64 )
      invalid_parameter_noinfo_noreturn();
    if ( v24 - Memory[0] >= 0x1000 )
    {
      if ( Memory[0] & 0x1F )
        invalid_parameter_noinfo_noreturn();
      v14 = *(Memory[0] - 1);
      if ( v14 >= Memory[0] )
        invalid_parameter_noinfo_noreturn();
      if ( (Memory[0] - v14) < 8 )
        invalid_parameter_noinfo_noreturn();
      if ( (Memory[0] - v14) > 0x27 )
        invalid_parameter_noinfo_noreturn();
      v10 = *(Memory[0] - 1);
    }
    j_free(v10);
  }
  if ( v9 )
  {
    v15 = v3 - v9;
    if ( v15 > 0xFFFFFFFFFFFFFFFFui64 )
      invalid_parameter_noinfo_noreturn();
    if ( v15 >= 0x1000 )
    {
      if ( v9 & 0x1F )
        invalid_parameter_noinfo_noreturn();
      v16 = *(v9 - 1);
      if ( v16 >= v9 )
        invalid_parameter_noinfo_noreturn();
      v17 = v9 - v16;
      if ( v17 < 8 )
        invalid_parameter_noinfo_noreturn();
      if ( v17 > 0x27 )
        invalid_parameter_noinfo_noreturn();
      v9 = v16;
    }
    j_free(v9);
  }
  return v2;
}
// 180008938: using guessed type __int64 qword_180008938;

//----- (0000000180001610) ----------------------------------------------------
void __fastcall sub_180001610(void **a1)
{
  void **v1; // rbx
  _BYTE *v2; // rcx
  unsigned __int64 v3; // rax
  _BYTE *v4; // rax
  unsigned __int64 v5; // rcx

  v1 = a1;
  v2 = *a1;
  if ( v2 )
  {
    v3 = v1[2] - v2;
    if ( v3 > 0xFFFFFFFFFFFFFFFFui64 )
      invalid_parameter_noinfo_noreturn();
    if ( v3 >= 0x1000 )
    {
      if ( v2 & 0x1F )
        invalid_parameter_noinfo_noreturn();
      v4 = *(v2 - 1);
      if ( v4 >= v2 )
        invalid_parameter_noinfo_noreturn();
      v5 = v2 - v4;
      if ( v5 < 8 )
        invalid_parameter_noinfo_noreturn();
      if ( v5 > 0x27 )
        invalid_parameter_noinfo_noreturn();
      v2 = v4;
    }
    j_free(v2);
    *v1 = 0i64;
    v1[1] = 0i64;
    v1[2] = 0i64;
  }
}

//----- (00000001800016A0) ----------------------------------------------------
char *__fastcall sub_1800016A0(__int64 *a1, unsigned __int8 *a2)
{
  __int64 *v2; // rbx
  unsigned __int8 *v3; // rdi
  unsigned __int64 v4; // rcx
  __int64 v5; // rdx
  __int64 v6; // r8
  unsigned __int8 *v7; // rdi
  char *result; // rax
  unsigned __int64 v9; // r8
  unsigned __int64 v10; // rcx
  size_t v11; // rdx
  _BYTE *v12; // rdx
  __int64 v13; // r8
  char *v14; // rdx
  unsigned __int64 v15; // r8
  unsigned __int64 v16; // rcx
  size_t v17; // rdx
  _BYTE *v18; // rcx

  v2 = a1;
  v3 = a2;
  v4 = a1[1];
  if ( a2 >= v4 || (v5 = *v2, *v2 > v3) )
  {
    v13 = v2[2];
    if ( v4 == v13 )
    {
      result = (v13 - v4);
      if ( v13 - v4 < 1 )
      {
        v14 = *v2;
        if ( *v2 - v4 - 1 < 1 )
        {
          std::_Xlength_error("vector<T> too long");
          __debugbreak();
        }
        v15 = v13 - v14;
        v16 = v4 - v14 + 1;
        v17 = (v15 >> 1) + v15;
        if ( -1i64 - (v15 >> 1) < v15 )
          v17 = 0i64;
        if ( v17 < v16 )
          v17 = v16;
        result = sub_1800017E0(v2, v17);
      }
    }
    v18 = v2[1];
    if ( v18 )
    {
      result = *v3;
      *v18 = result;
    }
  }
  else
  {
    v6 = v2[2];
    v7 = &v3[-v5];
    if ( v4 == v6 )
    {
      result = (v6 - v4);
      if ( v6 - v4 < 1 )
      {
        if ( v5 - v4 - 1 < 1 )
        {
          std::_Xlength_error("vector<T> too long");
          __debugbreak();
        }
        v9 = v6 - v5;
        v10 = v4 - v5 + 1;
        v11 = (v9 >> 1) + v9;
        if ( -1i64 - (v9 >> 1) < v9 )
          v11 = 0i64;
        if ( v11 < v10 )
          v11 = v10;
        result = sub_1800017E0(v2, v11);
      }
    }
    v12 = v2[1];
    if ( v12 )
    {
      result = *v2;
      *v12 = v7[*v2];
      ++v2[1];
      return result;
    }
  }
  ++v2[1];
  return result;
}
// 180005140: using guessed type void __stdcall std::_Xlength_error(const char *);

//----- (00000001800017E0) ----------------------------------------------------
char *__fastcall sub_1800017E0(__int64 a1, size_t a2)
{
  size_t v2; // rdi
  __int64 v3; // rsi
  _QWORD *v4; // rbx
  char *v5; // rcx
  __int64 v6; // rbp
  unsigned __int64 v7; // rax
  size_t v8; // rcx
  void *v9; // rax
  char *v10; // rax
  unsigned __int64 v11; // rcx
  char *result; // rax

  v2 = a2;
  v3 = a1;
  if ( a2 )
  {
    if ( a2 > 0xFFFFFFFFFFFFFFFFui64 )
    {
      std::_Xbad_alloc();
      __debugbreak();
    }
    if ( a2 < 0x1000 )
    {
      v4 = operator new(a2);
      if ( !v4 )
        invalid_parameter_noinfo_noreturn();
    }
    else
    {
      v8 = a2 + 39;
      if ( a2 + 39 <= a2 )
      {
        std::_Xbad_alloc();
        __debugbreak();
      }
      v9 = operator new(v8);
      if ( !v9 )
        invalid_parameter_noinfo_noreturn();
      v4 = ((v9 + 39) & 0xFFFFFFFFFFFFFFE0ui64);
      *(v4 - 1) = v9;
    }
  }
  else
  {
    v4 = 0i64;
  }
  memmove(v4, *v3, *(v3 + 8) - *v3);
  v5 = *v3;
  v6 = *(v3 + 8) - *v3;
  if ( *v3 )
  {
    v7 = *(v3 + 16) - v5;
    if ( v7 > 0xFFFFFFFFFFFFFFFFui64 )
      invalid_parameter_noinfo_noreturn();
    if ( v7 >= 0x1000 )
    {
      if ( v5 & 0x1F )
        invalid_parameter_noinfo_noreturn();
      v10 = *(v5 - 1);
      if ( v10 >= v5 )
        invalid_parameter_noinfo_noreturn();
      v11 = v5 - v10;
      if ( v11 < 8 )
        invalid_parameter_noinfo_noreturn();
      if ( v11 > 0x27 )
        invalid_parameter_noinfo_noreturn();
      v5 = v10;
    }
    j_free(v5);
  }
  *(v3 + 16) = v4 + v2;
  result = v4 + v6;
  *(v3 + 8) = v4 + v6;
  *v3 = v4;
  return result;
}
// 180005138: using guessed type void std::_Xbad_alloc(void);

//----- (0000000180001900) ----------------------------------------------------
_QWORD *__fastcall sub_180001900(__int64 a1, size_t a2)
{
  _QWORD *result; // rax
  size_t v3; // rcx
  void *v4; // rax
  void *v5; // rcx

  if ( !a2 )
    return 0i64;
  if ( a2 > 0xFFFFFFFFFFFFFFFFui64 )
  {
    std::_Xbad_alloc();
    __debugbreak();
  }
  if ( a2 < 0x1000 )
  {
    result = operator new(a2);
    if ( !result )
      invalid_parameter_noinfo_noreturn();
  }
  else
  {
    v3 = a2 + 39;
    if ( a2 + 39 <= a2 )
    {
      std::_Xbad_alloc();
      __debugbreak();
    }
    v4 = operator new(v3);
    v5 = v4;
    if ( !v4 )
      invalid_parameter_noinfo_noreturn();
    result = ((v4 + 39) & 0xFFFFFFFFFFFFFFE0ui64);
    *(result - 1) = v5;
  }
  return result;
}
// 180005138: using guessed type void std::_Xbad_alloc(void);

//----- (0000000180001970) ----------------------------------------------------
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
  return 1;
}

//----- (0000000180001980) ----------------------------------------------------
void *sub_180001980()
{
  return &unk_180008958;
}

//----- (0000000180001990) ----------------------------------------------------
_QWORD *__fastcall sub_180001990(_QWORD *a1, __int64 a2)
{
  _QWORD *v2; // rbx
  __int64 v3; // rax
  _QWORD *v4; // rdx

  v2 = a1;
  v3 = a2;
  v4 = a1 + 1;
  *a1 = &std::exception::`vftable';
  *v4 = 0i64;
  v4[1] = 0i64;
  __std_exception_copy(v3 + 8);
  return v2;
}
// 1800051B8: using guessed type __int64 __fastcall __std_exception_copy(_QWORD);
// 1800053B0: using guessed type void *std::exception::`vftable';

//----- (00000001800019D0) ----------------------------------------------------
const char *__fastcall sub_1800019D0(__int64 a1)
{
  const char *result; // rax

  result = "Unknown exception";
  if ( *(a1 + 8) )
    result = *(a1 + 8);
  return result;
}

//----- (00000001800019F0) ----------------------------------------------------
void *__fastcall sub_1800019F0(void *Memory, char a2)
{
  void *v2; // rdi
  char v3; // bl

  v2 = Memory;
  *Memory = &std::exception::`vftable';
  v3 = a2;
  __std_exception_destroy(Memory + 8);
  if ( v3 & 1 )
    j_j_free(v2);
  return v2;
}
// 1800051C0: using guessed type __int64 __fastcall __std_exception_destroy(_QWORD);
// 1800053B0: using guessed type void *std::exception::`vftable';

//----- (0000000180001A40) ----------------------------------------------------
__int64 __fastcall sub_180001A40(_QWORD *a1)
{
  *a1 = &std::exception::`vftable';
  return __std_exception_destroy(a1 + 1);
}
// 1800051C0: using guessed type __int64 __fastcall __std_exception_destroy(_QWORD);
// 1800053B0: using guessed type void *std::exception::`vftable';

//----- (0000000180001A60) ----------------------------------------------------
void __fastcall sub_180001A60(__int64 a1)
{
  __int64 v1; // rcx
  void (__fastcall ***v2)(_QWORD, signed __int64); // rax

  v1 = *(a1 + 8);
  if ( v1 )
  {
    v2 = (*(*v1 + 16i64))(v1);
    if ( v2 )
      (**v2)(v2, 1i64);
  }
}

//----- (0000000180001AA0) ----------------------------------------------------
__int64 __fastcall sub_180001AA0(__int64 a1)
{
  __int64 v1; // rbx

  v1 = a1 + 168;
  sub_180001CB0(a1 + 168);
  return std::basic_ios<char,std::char_traits<char>>::~basic_ios<char,std::char_traits<char>>(v1);
}
// 1800050F8: using guessed type __int64 __fastcall std::basic_ios<char,std::char_traits<char>>::~basic_ios<char,std::char_traits<char>>(_QWORD);

//----- (0000000180001AD0) ----------------------------------------------------
void WriteToLog1(__int64 a1, __int64 a2, ...)
{
  __int64 v2; // rsi
  signed __int64 v3; // rax
  signed __int64 v4; // rdi
  char *v5; // rbx
  _QWORD *v6; // rax
  __int64 v7; // rax
  char v8; // [rsp+50h] [rbp-348h]
  char v9; // [rsp+F8h] [rbp-2A0h]
  char Dst[512]; // [rsp+160h] [rbp-238h]
  va_list va; // [rsp+3B0h] [rbp+18h]

  va_start(va, a2);
  if ( a2 )
  {
    v2 = a2;
    memset(Dst, 0, 0x200ui64);
    v3 = -1i64;
    do
      ++v3;
    while ( Dst[v3] );
    v4 = 512 - v3;
    v5 = &Dst[v3];
    v6 = sub_180001980();
    _stdio_common_vsnprintf_s(*v6, v5, v4, 512i64, v2, 0i64, va);
    memset(&v8, 0, 0x108ui64);
    sub_180001D80(&v8);
    v7 = WriteToLog(&v8, Dst);
    WriteToLog(v7, "\n");
    sub_180001CB0(&v9);
    std::basic_ios<char,std::char_traits<char>>::~basic_ios<char,std::char_traits<char>>(&v9);
  }
}
// 1800031A0: using guessed type __int64 __fastcall WriteToLog(_QWORD, _QWORD);
// 1800050F8: using guessed type __int64 __fastcall std::basic_ios<char,std::char_traits<char>>::~basic_ios<char,std::char_traits<char>>(_QWORD);
// 1800052D0: using guessed type __int64 __fastcall _stdio_common_vsnprintf_s(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 180001AD0: using guessed type char Dst[512];

//----- (0000000180001C10) ----------------------------------------------------
void __fastcall sub_180001C10(_QWORD *a1)
{
  unsigned __int64 v1; // rax
  _QWORD *v2; // rbx
  char *v3; // rcx
  unsigned __int64 v4; // rax
  char *v5; // rax
  unsigned __int64 v6; // rcx

  v1 = a1[3];
  v2 = a1;
  if ( v1 >= 0x10 )
  {
    v3 = *a1;
    v4 = v1 + 1;
    if ( v4 > 0xFFFFFFFFFFFFFFFFui64 )
      invalid_parameter_noinfo_noreturn();
    if ( v4 >= 0x1000 )
    {
      if ( v3 & 0x1F )
        invalid_parameter_noinfo_noreturn();
      v5 = *(v3 - 1);
      if ( v5 >= v3 )
        invalid_parameter_noinfo_noreturn();
      v6 = v3 - v5;
      if ( v6 < 8 )
        invalid_parameter_noinfo_noreturn();
      if ( v6 > 0x27 )
        invalid_parameter_noinfo_noreturn();
      v3 = v5;
    }
    j_free(v3);
  }
  v2[3] = 15i64;
  v2[2] = 0i64;
  if ( v2[3] >= 0x10ui64 )
    v2 = *v2;
  *v2 = 0;
}

//----- (0000000180001CB0) ----------------------------------------------------
__int64 __fastcall sub_180001CB0(__int64 a1)
{
  __int64 v1; // rdi
  __int64 v2; // rdx
  __int64 v3; // rbx
  _QWORD *v4; // rcx
  __int64 v5; // r8
  __int64 v6; // rdx

  v1 = a1;
  *(*(*(a1 - 168) + 4i64) + a1 - 168) = &std::basic_ofstream<char,std::char_traits<char>>::`vftable';
  v2 = *(*(a1 - 168) + 4i64);
  *(v2 + a1 - 172) = v2 - 168;
  v3 = a1 - 160;
  *(a1 - 160) = &std::basic_filebuf<char,std::char_traits<char>>::`vftable';
  if ( *(a1 - 160 + 128) )
  {
    v4 = *(v3 + 24);
    if ( *v4 == v3 + 112 )
    {
      v5 = *(v3 + 144);
      v6 = *(v3 + 136);
      *v4 = v6;
      **(v3 + 56) = v6;
      **(v3 + 80) = v5 - v6;
    }
  }
  if ( *(v3 + 124) )
    sub_180002E90(v3);
  std::basic_streambuf<char,std::char_traits<char>>::~basic_streambuf<char,std::char_traits<char>>(v3);
  return std::basic_ostream<char,std::char_traits<char>>::~basic_ostream<char,std::char_traits<char>>(v1 - 152);
}
// 180005100: using guessed type __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::~basic_streambuf<char,std::char_traits<char>>(_QWORD);
// 180005120: using guessed type __int64 __fastcall std::basic_ostream<char,std::char_traits<char>>::~basic_ostream<char,std::char_traits<char>>(_QWORD);
// 180005600: using guessed type void *std::basic_filebuf<char,std::char_traits<char>>::`vftable';
// 180005680: using guessed type void *std::basic_ofstream<char,std::char_traits<char>>::`vftable';

//----- (0000000180001D80) ----------------------------------------------------
_QWORD *__fastcall sub_180001D80(_QWORD *a1)
{
  _QWORD *v1; // rsi
  const char *v2; // rdi
  signed int v3; // ST20_4

  v1 = a1;
  v2 = qword_180008928;
  *a1 = &unk_1800056A0;
  std::basic_ios<char,std::char_traits<char>>::basic_ios<char,std::char_traits<char>>(a1 + 21);
  v3 = 1;
  std::basic_ostream<char,std::char_traits<char>>::basic_ostream<char,std::char_traits<char>>(
    v1,
    v1 + 1,
    0i64,
    0i64,
    v3);
  *(v1 + *(*v1 + 4i64)) = &std::basic_ofstream<char,std::char_traits<char>>::`vftable';
  *(v1 + *(*v1 + 4i64) - 4) = *(*v1 + 4i64) - 168;
  std::basic_streambuf<char,std::char_traits<char>>::basic_streambuf<char,std::char_traits<char>>(v1 + 1);
  v1[1] = &std::basic_filebuf<char,std::char_traits<char>>::`vftable';
  *(v1 + 132) = 0;
  *(v1 + 121) = 0;
  std::basic_streambuf<char,std::char_traits<char>>::_Init(v1 + 1);
  v1[17] = 0i64;
  *(v1 + 124) = qword_180008950;
  v1[14] = 0i64;
  if ( !sub_180002F10((v1 + 1), v2) )
    std::basic_ios<char,std::char_traits<char>>::setstate(v1 + *(*v1 + 4i64), 2i64, 0i64);
  return v1;
}
// 1800050B0: using guessed type __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::basic_streambuf<char,std::char_traits<char>>(_QWORD);
// 1800050C0: using guessed type __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::_Init(_QWORD);
// 1800050D0: using guessed type __int64 __fastcall std::basic_ios<char,std::char_traits<char>>::setstate(_QWORD, _QWORD, _QWORD);
// 1800050D8: using guessed type __int64 __fastcall std::basic_ios<char,std::char_traits<char>>::basic_ios<char,std::char_traits<char>>(_QWORD);
// 1800050E0: using guessed type __int64 __fastcall std::basic_ostream<char,std::char_traits<char>>::basic_ostream<char,std::char_traits<char>>(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 180005600: using guessed type void *std::basic_filebuf<char,std::char_traits<char>>::`vftable';
// 180005680: using guessed type void *std::basic_ofstream<char,std::char_traits<char>>::`vftable';
// 180008928: using guessed type __int64 qword_180008928;
// 180008950: using guessed type __int64 qword_180008950;

//----- (0000000180001E90) ----------------------------------------------------
char __fastcall sub_180001E90(__int64 a1, __int64 a2)
{
  __int64 v2; // rbx
  std::codecvt_base *v3; // rax
  std::codecvt_base *v4; // rdi
  char result; // al

  v2 = a1;
  v3 = sub_180003380(a2);
  v4 = v3;
  result = std::codecvt_base::always_noconv(v3);
  if ( result )
  {
    *(v2 + 104) = 0i64;
  }
  else
  {
    *(v2 + 104) = v4;
    result = std::basic_streambuf<char,std::char_traits<char>>::_Init(v2);
  }
  return result;
}
// 180003380: using guessed type __int64 __fastcall sub_180003380(_QWORD);
// 1800050C0: using guessed type __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::_Init(_QWORD);
// 180005128: using guessed type bool std::codecvt_base::always_noconv(std::codecvt_base *__hidden this);

//----- (0000000180001EE0) ----------------------------------------------------
signed __int64 __fastcall sub_180001EE0(_QWORD *a1)
{
  _QWORD *v1; // rbx
  signed __int64 result; // rax

  v1 = a1;
  if ( a1[16] && (*(*a1 + 24i64))(a1, 0xFFFFFFFFi64) != -1 && fflush(v1[16]) < 0 )
    result = 0xFFFFFFFFi64;
  else
    result = 0i64;
  return result;
}

//----- (0000000180001F30) ----------------------------------------------------
__int64 __fastcall sub_180001F30(__int64 a1, char *a2, size_t a3)
{
  __int64 v3; // rbx
  size_t v4; // r9
  FILE *v5; // rcx
  int v6; // er8

  v3 = a1;
  v4 = a3;
  v5 = *(a1 + 128);
  if ( !v5 )
    return 0i64;
  v6 = a2 || a3 ? 0 : 4;
  if ( setvbuf(v5, a2, v6, v4) )
    return 0i64;
  sub_180002DD0(v3, *(v3 + 128), 1);
  return v3;
}

//----- (0000000180001F90) ----------------------------------------------------
_QWORD *__fastcall sub_180001F90(__int64 a1, _QWORD *a2, __int64 *a3)
{
  bool v3; // zf
  __int64 *v4; // r14
  _QWORD *v5; // rbx
  __int64 v6; // rsi
  __int64 v7; // rdi
  __int64 v8; // rcx
  fpos_t Pos; // [rsp+20h] [rbp-28h]

  v3 = *(a1 + 128) == 0i64;
  v4 = a3;
  v5 = a2;
  v6 = *a3;
  v7 = a1;
  Pos = a3[1];
  if ( v3
    || !sub_180002BF0()
    || fsetpos(*(v7 + 128), &Pos)
    || v6 && fseeki64(*(v7 + 128), v6, 1)
    || fgetpos(*(v7 + 128), &Pos) )
  {
    *v5 = std::_BADOFF;
    v5[1] = 0i64;
    v5[2] = 0i64;
  }
  else
  {
    *(v7 + 116) = v4[2];
    std::basic_filebuf<char,std::char_traits<char>>::_Reset_back(v7);
    v8 = *(v7 + 116);
    v5[1] = Pos;
    *v5 = 0i64;
    v5[2] = v8;
  }
  return v5;
}
// 180002BC0: using guessed type __int64 __fastcall std::basic_filebuf<char,std::char_traits<char>>::_Reset_back(_QWORD);
// 180002BF0: using guessed type __int64 sub_180002BF0(void);
// 180005168: using guessed type const __int64 std::_BADOFF;

//----- (0000000180002080) ----------------------------------------------------
_QWORD *__fastcall sub_180002080(__int64 a1, _QWORD *a2, __int64 a3, int a4)
{
  signed __int64 v4; // r14
  int v5; // ebp
  __int64 v6; // rsi
  _QWORD *v7; // rdi
  __int64 v8; // rbx
  _QWORD *v9; // rax
  __int64 v10; // rdx
  __int64 v11; // r8
  __int64 v12; // rcx
  fpos_t Pos; // [rsp+20h] [rbp-38h]

  v4 = a1 + 112;
  v5 = a4;
  v6 = a3;
  v7 = a2;
  v8 = a1;
  if ( **(a1 + 56) == a1 + 112 && a4 == 1 && !*(a1 + 104) )
    v6 = a3 - 1;
  if ( !*(a1 + 128)
    || !sub_180002BF0()
    || (v6 || v5 != 1) && fseeki64(*(v8 + 128), v6, v5)
    || fgetpos(*(v8 + 128), &Pos) )
  {
    *v7 = std::_BADOFF;
    v7[1] = 0i64;
    v7[2] = 0i64;
  }
  else
  {
    v9 = *(v8 + 24);
    if ( *v9 == v4 )
    {
      v10 = *(v8 + 136);
      v11 = *(v8 + 144);
      *v9 = v10;
      **(v8 + 56) = v10;
      **(v8 + 80) = v11 - v10;
    }
    v12 = *(v8 + 116);
    v7[1] = Pos;
    v7[2] = v12;
    *v7 = 0i64;
  }
  return v7;
}
// 180002BF0: using guessed type __int64 sub_180002BF0(void);
// 180005168: using guessed type const __int64 std::_BADOFF;

//----- (0000000180002190) ----------------------------------------------------
signed __int64 __fastcall sub_180002190(__int64 a1)
{
  __int64 v1; // rbx
  unsigned __int64 v2; // rcx
  signed int *v3; // rdx
  __int64 v4; // r8
  _QWORD *v5; // rcx
  unsigned __int8 *v6; // rdx
  signed __int64 result; // rax
  _QWORD *v8; // r8
  __int64 v9; // rdx
  __int64 v10; // rcx
  int v11; // eax
  unsigned int v12; // ebx
  int v13; // eax
  char *v14; // rdx
  void *v15; // r8
  signed int v16; // eax
  void **v17; // rdx
  char *v18; // rax
  unsigned __int64 v19; // r8
  __int64 v20; // rcx
  _BYTE *v21; // rax
  char *v22; // rax
  size_t v23; // rdi
  void **v24; // rax
  unsigned __int8 *v25; // rax
  unsigned __int8 v26; // al
  void **v27; // rcx
  __int64 v28; // r8
  int v29; // eax
  __int64 v30; // rdi
  void **v31; // rax
  unsigned __int64 v32; // rdx
  char *v33; // [rsp+30h] [rbp-1h]
  char *v34; // [rsp+38h] [rbp+7h]
  unsigned __int8 v35; // [rsp+40h] [rbp+Fh]
  char v36; // [rsp+41h] [rbp+10h]
  void *Dst; // [rsp+48h] [rbp+17h]
  unsigned __int64 v38; // [rsp+58h] [rbp+27h]
  unsigned __int64 v39; // [rsp+60h] [rbp+2Fh]

  v1 = a1;
  v2 = **(a1 + 56);
  if ( v2 && (v3 = *(v1 + 80), v4 = *v3, v2 < v2 + v4) )
  {
    *v3 = v4 - 1;
    v5 = *(v1 + 56);
    v6 = (*v5)++;
    result = *v6;
  }
  else if ( *(v1 + 128) )
  {
    v8 = *(v1 + 24);
    if ( *v8 == v1 + 112 )
    {
      v9 = *(v1 + 144);
      v10 = *(v1 + 136);
      *v8 = v10;
      **(v1 + 56) = v10;
      **(v1 + 80) = v9 - v10;
    }
    if ( *(v1 + 104) )
    {
      v39 = 15i64;
      v38 = 0i64;
      LOBYTE(Dst) = 0;
      while ( 1 )
      {
        while ( 1 )
        {
          v13 = fgetc(*(v1 + 128));
          if ( v13 == -1 )
            goto LABEL_51;
          sub_180002AA0(&Dst, 1ui64, v13);
          v14 = &Dst;
          if ( v39 >= 0x10 )
            v14 = Dst;
          v15 = &Dst;
          if ( v39 >= 0x10 )
            v15 = Dst;
          v34 = &v34;
          v33 = &v36;
          v16 = std::codecvt<char,char,_Mbstatet>::in(*(v1 + 104), v1 + 116, v15, &v14[v38], &v33, &v35);
          if ( v16 < 0 )
          {
LABEL_51:
            v17 = Dst;
            v12 = -1;
            goto LABEL_52;
          }
          if ( v16 <= 1 )
            break;
          if ( v16 != 3 )
            goto LABEL_51;
          if ( v38 >= 1 )
          {
            v17 = Dst;
            if ( v39 < 0x10 )
            {
              v25 = &Dst;
            }
            else
            {
              v25 = Dst;
              if ( !Dst )
              {
                v35 = Dst;
                *errno() = 22;
                invalid_parameter_noinfo();
                v17 = Dst;
                v26 = v35;
LABEL_43:
                v12 = v26;
                goto LABEL_52;
              }
            }
            v26 = *v25;
            v35 = v26;
            goto LABEL_43;
          }
        }
        v17 = Dst;
        if ( v34 != &v35 )
          break;
        v18 = &Dst;
        v19 = v39;
        if ( v39 >= 0x10 )
          v18 = Dst;
        v20 = v33 - v18;
        if ( v38 > v33 - v18 )
        {
          if ( v33 != v18 )
          {
            v22 = &Dst;
            if ( v39 >= 0x10 )
              v22 = Dst;
            v23 = v38 - v20;
            if ( v38 != v20 )
            {
              memmove(v22, &v22[v20], v23);
              v19 = v39;
              v17 = Dst;
            }
            v38 = v23;
            v24 = &Dst;
            if ( v19 >= 0x10 )
              v24 = v17;
            *(v24 + v23) = 0;
          }
        }
        else
        {
          v38 = 0i64;
          v21 = &Dst;
          if ( v39 >= 0x10 )
            v21 = Dst;
          *v21 = 0;
        }
      }
      v27 = &Dst;
      if ( v39 >= 0x10 )
        LODWORD(v27) = Dst;
      v28 = v33;
      v29 = v27 + v38 - v33;
      v30 = v29;
      if ( v29 > 0 )
      {
        while ( 1 )
        {
          ungetc(*(--v30 + v28), *(v1 + 128));
          if ( v30 <= 0 )
            break;
          v28 = v33;
        }
        v17 = Dst;
      }
      v12 = v35;
LABEL_52:
      if ( v39 >= 0x10 )
      {
        if ( v39 + 1 > 0xFFFFFFFFFFFFFFFFui64 )
          invalid_parameter_noinfo_noreturn();
        if ( v39 + 1 >= 0x1000 )
        {
          if ( Dst & 0x1F )
            invalid_parameter_noinfo_noreturn();
          v31 = *(v17 - 1);
          if ( v31 >= v17 )
            invalid_parameter_noinfo_noreturn();
          v32 = v17 - v31;
          if ( v32 < 8 )
            invalid_parameter_noinfo_noreturn();
          if ( v32 > 0x27 )
            invalid_parameter_noinfo_noreturn();
          v17 = v31;
        }
        j_free(v17);
      }
    }
    else
    {
      v11 = fgetc(*(v1 + 128));
      if ( v11 == -1 )
        v12 = -1;
      else
        v12 = v11;
    }
    result = v12;
  }
  else
  {
    result = 0xFFFFFFFFi64;
  }
  return result;
}
// 180005180: using guessed type __int64 __fastcall std::codecvt<char,char,_Mbstatet>::in(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000001800024D0) ----------------------------------------------------
signed __int64 __fastcall sub_1800024D0(__int64 a1)
{
  signed int **v1; // rbx
  unsigned __int8 *v2; // rcx
  unsigned int v4; // edi

  v1 = a1;
  v2 = **(a1 + 56);
  if ( v2 && v2 < &v2[*v1[10]] )
    return *v2;
  v4 = (*(*v1 + 7))(v1);
  if ( v4 == -1 )
    return 0xFFFFFFFFi64;
  (*(*v1 + 4))(v1, v4);
  return v4;
}

//----- (0000000180002540) ----------------------------------------------------
signed __int64 __fastcall sub_180002540(__int64 a1, unsigned int a2)
{
  __int64 v2; // rbx
  unsigned int v3; // edi
  unsigned __int64 v4; // rcx
  signed __int64 result; // rax
  FILE *v6; // rdx
  _QWORD *v7; // r8
  _BYTE *v8; // rdx
  _QWORD *v9; // r9

  v2 = a1;
  v3 = a2;
  v4 = **(a1 + 56);
  if ( !v4 || **(v2 + 24) >= v4 || a2 != -1 && *(v4 - 1) != a2 )
  {
    v6 = *(v2 + 128);
    if ( v6 && v3 != -1 )
    {
      if ( !*(v2 + 104) && ungetc(v3, v6) != -1 )
        return v3;
      v7 = *(v2 + 56);
      v8 = (v2 + 112);
      if ( *v7 != v2 + 112 )
      {
        v9 = *(v2 + 24);
        *v8 = v3;
        if ( *v9 != v8 )
        {
          *(v2 + 136) = *v9;
          *(v2 + 144) = *v7 + **(v2 + 80);
        }
        *v9 = v8;
        **(v2 + 56) = v8;
        **(v2 + 80) = 1;
        return v3;
      }
    }
    return 0xFFFFFFFFi64;
  }
  ++**(v2 + 80);
  --**(v2 + 56);
  result = 0i64;
  if ( a2 != -1 )
    result = a2;
  return result;
}

//----- (0000000180002620) ----------------------------------------------------
signed __int64 __fastcall sub_180002620(__int64 a1, unsigned int a2)
{
  unsigned int v2; // esi
  __int64 v3; // rbx
  signed __int64 result; // rax
  unsigned __int64 v5; // rdx
  signed int *v6; // rax
  __int64 v7; // r8
  _QWORD *v8; // rdx
  _BYTE *v9; // r8
  _QWORD *v10; // r8
  __int64 v11; // rdx
  __int64 v12; // rcx
  int v13; // eax
  unsigned int v14; // ebx
  void **v15; // r8
  unsigned __int64 v16; // r9
  void **v17; // rcx
  void **v18; // rdx
  signed int v19; // eax
  void **v20; // rax
  __int64 v21; // rdi
  const void *v22; // rcx
  size_t v23; // rax
  int v24; // eax
  unsigned __int64 v25; // r9
  void **v26; // rax
  unsigned __int64 v27; // r8
  void **v28; // [rsp+30h] [rbp-1h]
  char *v29; // [rsp+38h] [rbp+7h]
  char v30; // [rsp+40h] [rbp+Fh]
  char v31; // [rsp+41h] [rbp+10h]
  void *Str; // [rsp+48h] [rbp+17h]
  char v33; // [rsp+50h] [rbp+1Fh]
  unsigned __int64 v34; // [rsp+58h] [rbp+27h]
  unsigned __int64 v35; // [rsp+60h] [rbp+2Fh]

  v2 = a2;
  v3 = a1;
  if ( a2 == -1 )
    return 0i64;
  v5 = **(a1 + 64);
  if ( v5 && (v6 = *(a1 + 88), v7 = *v6, v5 < v5 + v7) )
  {
    *v6 = v7 - 1;
    v8 = *(a1 + 64);
    v9 = (*v8)++;
    *v9 = v2;
    result = v2;
  }
  else if ( *(a1 + 128) )
  {
    v10 = *(a1 + 24);
    if ( *v10 == a1 + 112 )
    {
      v11 = *(a1 + 144);
      v12 = *(a1 + 136);
      *v10 = v12;
      **(v3 + 56) = v12;
      **(v3 + 80) = v11 - v12;
    }
    if ( *(v3 + 104) )
    {
      v30 = v2;
      v35 = 15i64;
      Str = 0i64;
      v34 = 8i64;
      v33 = 0;
LABEL_15:
      v15 = Str;
      v16 = v35;
      while ( 1 )
      {
        v17 = &Str;
        if ( v16 >= 0x10 )
          v17 = v15;
        v18 = &Str;
        if ( v16 >= 0x10 )
          v18 = v15;
        v29 = &v28;
        v28 = &v17[v34 / 8];
        v19 = std::codecvt<char,char,_Mbstatet>::out(*(v3 + 104), v3 + 116, &v30, &v31, &v29, v18);
        if ( v19 < 0 )
          goto LABEL_37;
        if ( v19 > 1 )
          break;
        v20 = &Str;
        v15 = Str;
        v16 = v35;
        if ( v35 >= 0x10 )
          v20 = Str;
        v21 = v28 - v20;
        if ( v28 != v20 )
        {
          v22 = &Str;
          if ( v35 >= 0x10 )
            v22 = Str;
          v23 = fwrite(v22, 1ui64, v28 - v20, *(v3 + 128));
          v16 = v35;
          v15 = Str;
          if ( v21 != v23 )
            goto LABEL_38;
        }
        *(v3 + 113) = 1;
        if ( v29 != &v30 )
        {
          v14 = v2;
          goto LABEL_39;
        }
        if ( !v21 )
        {
          if ( v34 < 0x20 )
          {
            sub_180002AA0(&Str, 8ui64, 0);
            goto LABEL_15;
          }
          goto LABEL_38;
        }
      }
      if ( v19 != 3 )
      {
LABEL_37:
        v16 = v35;
        v15 = Str;
LABEL_38:
        v14 = -1;
        goto LABEL_39;
      }
      v24 = fputc(v30, *(v3 + 128));
      v14 = -1;
      if ( v24 != -1 )
        v14 = v2;
      v16 = v35;
      v15 = Str;
LABEL_39:
      if ( v16 >= 0x10 )
      {
        v25 = v16 + 1;
        if ( v25 > 0xFFFFFFFFFFFFFFFFui64 )
          invalid_parameter_noinfo_noreturn();
        if ( v25 >= 0x1000 )
        {
          if ( Str & 0x1F )
            invalid_parameter_noinfo_noreturn();
          v26 = *(v15 - 1);
          if ( v26 >= v15 )
            invalid_parameter_noinfo_noreturn();
          v27 = v15 - v26;
          if ( v27 < 8 )
            invalid_parameter_noinfo_noreturn();
          if ( v27 > 0x27 )
            invalid_parameter_noinfo_noreturn();
          v15 = v26;
        }
        j_free(v15);
      }
    }
    else
    {
      v13 = fputc(v2, *(v3 + 128));
      v14 = -1;
      if ( v13 != -1 )
        v14 = v2;
    }
    result = v14;
  }
  else
  {
    result = 0xFFFFFFFFi64;
  }
  return result;
}
// 1800050F0: using guessed type __int64 __fastcall std::codecvt<char,char,_Mbstatet>::out(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000001800028E0) ----------------------------------------------------
void __fastcall sub_1800028E0(__int64 a1)
{
  FILE *v1; // rcx

  v1 = *(a1 + 128);
  if ( v1 )
    unlock_file(v1);
}

//----- (0000000180002900) ----------------------------------------------------
void __fastcall sub_180002900(__int64 a1)
{
  FILE *v1; // rcx

  v1 = *(a1 + 128);
  if ( v1 )
    lock_file(v1);
}

//----- (0000000180002920) ----------------------------------------------------
__int64 __fastcall sub_180002920(_QWORD *a1)
{
  _QWORD *v1; // rbx
  _QWORD *v2; // rcx
  __int64 v3; // r8
  __int64 v4; // rdx

  v1 = a1;
  *a1 = &std::basic_filebuf<char,std::char_traits<char>>::`vftable';
  if ( a1[16] )
  {
    v2 = a1[3];
    if ( *v2 == v1 + 14 )
    {
      v3 = v1[18];
      v4 = v1[17];
      *v2 = v4;
      *v1[7] = v4;
      *v1[10] = v3 - v4;
    }
  }
  if ( *(v1 + 124) )
    sub_180002E90(v1);
  return std::basic_streambuf<char,std::char_traits<char>>::~basic_streambuf<char,std::char_traits<char>>(v1);
}
// 180005100: using guessed type __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::~basic_streambuf<char,std::char_traits<char>>(_QWORD);
// 180005600: using guessed type void *std::basic_filebuf<char,std::char_traits<char>>::`vftable';

//----- (00000001800029A0) ----------------------------------------------------
char *__fastcall sub_1800029A0(__int64 a1, char a2)
{
  char *v2; // rsi
  char v3; // di

  v2 = (a1 - 168);
  v3 = a2;
  sub_180001CB0(a1);
  std::basic_ios<char,std::char_traits<char>>::~basic_ios<char,std::char_traits<char>>(v2 + 168);
  if ( v3 & 1 )
    j_j_free(v2);
  return v2;
}
// 1800050F8: using guessed type __int64 __fastcall std::basic_ios<char,std::char_traits<char>>::~basic_ios<char,std::char_traits<char>>(_QWORD);

//----- (0000000180002A00) ----------------------------------------------------
_QWORD **__fastcall sub_180002A00(void *Memory, char a2)
{
  char v2; // di
  _QWORD **v3; // rbx
  void **v4; // r8
  __int64 v5; // rdx
  void *v6; // rcx

  v2 = a2;
  v3 = Memory;
  *Memory = &std::basic_filebuf<char,std::char_traits<char>>::`vftable';
  if ( *(Memory + 16) )
  {
    v4 = *(Memory + 3);
    if ( *v4 == Memory + 112 )
    {
      v5 = *(Memory + 18);
      v6 = *(Memory + 17);
      *v4 = v6;
      *v3[7] = v6;
      *v3[10] = v5 - v6;
    }
  }
  if ( *(v3 + 124) )
    sub_180002E90(v3);
  std::basic_streambuf<char,std::char_traits<char>>::~basic_streambuf<char,std::char_traits<char>>(v3);
  if ( v2 & 1 )
    j_j_free(v3);
  return v3;
}
// 180005100: using guessed type __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::~basic_streambuf<char,std::char_traits<char>>(_QWORD);
// 180005600: using guessed type void *std::basic_filebuf<char,std::char_traits<char>>::`vftable';

//----- (0000000180002AA0) ----------------------------------------------------
_QWORD *__fastcall sub_180002AA0(_QWORD *a1, unsigned __int64 a2, char a3)
{
  char v3; // bp
  size_t v4; // r8
  unsigned __int64 v5; // rsi
  _QWORD *v6; // rbx
  unsigned __int64 v7; // rdi
  __int64 v8; // rcx
  _QWORD *result; // rax
  _QWORD *v10; // rax
  _QWORD *v11; // rax

  v3 = a3;
  v4 = a1[2];
  v5 = a2;
  v6 = a1;
  if ( -1i64 - v4 <= a2 )
  {
    std::_Xlength_error("string too long");
    __debugbreak();
  }
  if ( !a2 )
    return v6;
  v7 = v4 + a2;
  if ( v4 + a2 > 0xFFFFFFFFFFFFFFFEui64 )
  {
    std::_Xlength_error("string too long");
    __debugbreak();
  }
  if ( a1[3] < v7 )
  {
    sub_180002FE0(a1, v7, v4);
    if ( !v7 )
      return v6;
LABEL_8:
    v8 = v6[2];
    if ( v5 == 1 )
    {
      if ( v6[3] < 0x10ui64 )
        *(v6 + v8) = v3;
      else
        *(*v6 + v8) = v3;
    }
    else
    {
      if ( v6[3] < 0x10ui64 )
        v10 = v6;
      else
        v10 = *v6;
      memset(v10 + v8, v3, v5);
    }
    v6[2] = v7;
    if ( v6[3] < 0x10ui64 )
      v11 = v6;
    else
      v11 = *v6;
    *(v11 + v7) = 0;
    return v6;
  }
  if ( v7 )
    goto LABEL_8;
  a1[2] = 0i64;
  if ( a1[3] < 0x10ui64 )
  {
    result = v6;
    *a1 = 0;
  }
  else
  {
    **a1 = 0;
    result = v6;
  }
  return result;
}
// 180005140: using guessed type void __stdcall std::_Xlength_error(const char *);

//----- (0000000180002DD0) ----------------------------------------------------
__int64 __fastcall sub_180002DD0(__int64 a1, __int64 a2, int a3)
{
  __int64 v3; // rdi
  _QWORD *v4; // rbx
  __int64 v5; // rax
  __int64 v6; // rax
  __int64 v7; // rax
  __int64 result; // rax
  __int128 v9; // [rsp+20h] [rbp-28h]
  __int64 v10; // [rsp+30h] [rbp-18h]

  *(a1 + 113) = 0;
  v3 = a2;
  v4 = a1;
  *(a1 + 124) = a3 == 1;
  std::basic_streambuf<char,std::char_traits<char>>::_Init(a1);
  if ( v3 )
  {
    v9 = 0ui64;
    v10 = 0i64;
    get_stream_buffer_pointers(v3, &v9, &v9 + 8, &v10);
    v5 = v9;
    v4[3] = v9;
    v4[4] = v5;
    v6 = *(&v9 + 1);
    v4[7] = *(&v9 + 1);
    v4[8] = v6;
    v7 = v10;
    v4[10] = v10;
    v4[11] = v7;
  }
  result = qword_180008950;
  *(v4 + 116) = qword_180008950;
  v4[16] = v3;
  v4[13] = 0i64;
  return result;
}
// 1800050C0: using guessed type __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::_Init(_QWORD);
// 1800052C8: using guessed type __int64 __fastcall get_stream_buffer_pointers(_QWORD, _QWORD, _QWORD, _QWORD);
// 180008950: using guessed type __int64 qword_180008950;

//----- (0000000180002E90) ----------------------------------------------------
__int64 __fastcall sub_180002E90(__int64 a1)
{
  __int64 v1; // rbx
  __int64 v2; // rsi
  __int64 result; // rax

  v1 = a1;
  if ( *(a1 + 128) )
  {
    v2 = a1;
    if ( !sub_180002BF0() )
      v2 = 0i64;
    if ( fclose(*(v1 + 128)) )
      v2 = 0i64;
  }
  else
  {
    v2 = 0i64;
  }
  *(v1 + 124) = 0;
  *(v1 + 113) = 0;
  std::basic_streambuf<char,std::char_traits<char>>::_Init(v1);
  result = v2;
  *(v1 + 116) = qword_180008950;
  *(v1 + 128) = 0i64;
  *(v1 + 104) = 0i64;
  return result;
}
// 180002BF0: using guessed type __int64 sub_180002BF0(void);
// 1800050C0: using guessed type __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::_Init(_QWORD);
// 180008950: using guessed type __int64 qword_180008950;

//----- (0000000180002F10) ----------------------------------------------------
__int64 __fastcall sub_180002F10(__int64 a1, const char *a2)
{
  __int64 v2; // rbx
  struct _iobuf *v3; // rax
  __int64 v4; // rax
  std::codecvt_base *v5; // rdi
  void (__fastcall ***v6)(_QWORD, signed __int64); // rax
  char v8; // [rsp+28h] [rbp-20h]
  __int64 v9; // [rsp+30h] [rbp-18h]

  v2 = a1;
  if ( *(a1 + 128) )
    return 0i64;
  v3 = std::_Fiopen(a2, 10, 64);
  if ( !v3 )
    return 0i64;
  sub_180002DD0(v2, v3, 1);
  v4 = std::basic_streambuf<char,std::char_traits<char>>::getloc(v2, &v8);
  v5 = sub_180003380(v4);
  if ( std::codecvt_base::always_noconv(v5) )
  {
    *(v2 + 104) = 0i64;
  }
  else
  {
    *(v2 + 104) = v5;
    std::basic_streambuf<char,std::char_traits<char>>::_Init(v2);
  }
  if ( v9 )
  {
    v6 = (*(*v9 + 16i64))(v9);
    if ( v6 )
      (**v6)(v6, 1i64);
  }
  return v2;
}
// 180003380: using guessed type __int64 __fastcall sub_180003380(_QWORD);
// 1800050B8: using guessed type __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::getloc(_QWORD, _QWORD);
// 1800050C0: using guessed type __int64 __fastcall std::basic_streambuf<char,std::char_traits<char>>::_Init(_QWORD);
// 180005128: using guessed type bool std::codecvt_base::always_noconv(std::codecvt_base *__hidden this);
// 180005178: using guessed type struct _iobuf *__stdcall std::_Fiopen(const char *, _DWORD, _DWORD);

//----- (0000000180002FE0) ----------------------------------------------------
char *__fastcall sub_180002FE0(void *Src, signed __int64 a2, size_t a3)
{
  size_t v3; // r14
  char **v4; // rbx
  signed __int64 v5; // rdi
  unsigned __int64 v6; // r8
  unsigned __int64 v7; // rcx
  size_t v8; // rcx
  _QWORD *v9; // rsi
  size_t v10; // rax
  void *v11; // rax
  char **v12; // rdx
  unsigned __int64 v13; // rax
  unsigned __int64 v14; // rax
  char *v15; // rcx
  char *v16; // rax
  unsigned __int64 v17; // rcx
  char *result; // rax

  v3 = a3;
  v4 = Src;
  v5 = a2 | 0xF;
  if ( (a2 | 0xFui64) <= 0xFFFFFFFFFFFFFFFEui64 )
  {
    v6 = *(Src + 3);
    v7 = *(Src + 3) >> 1;
    if ( v7 > (v5 * 0xAAAAAAAAAAAAAAABui64 >> 64) >> 1 )
    {
      v5 = -2i64;
      if ( v6 <= -2i64 - v7 )
        v5 = v6 + v7;
    }
  }
  else
  {
    v5 = a2;
  }
  v8 = v5 + 1;
  if ( v5 == -1 )
  {
    v9 = 0i64;
  }
  else
  {
    if ( v8 > 0xFFFFFFFFFFFFFFFFui64 )
      std::_Xbad_alloc();
    if ( v8 < 0x1000 )
    {
      v9 = operator new(v8);
      if ( !v9 )
        invalid_parameter_noinfo_noreturn();
    }
    else
    {
      v10 = v8 + 39;
      if ( v8 + 39 <= v8 )
        std::_Xbad_alloc();
      v11 = operator new(v10);
      if ( !v11 )
        invalid_parameter_noinfo_noreturn();
      v9 = ((v11 + 39) & 0xFFFFFFFFFFFFFFE0ui64);
      *(v9 - 1) = v11;
    }
  }
  if ( v3 )
  {
    v12 = v4[3] < 0x10 ? v4 : *v4;
    if ( v3 )
      memcpy(v9, v12, v3);
  }
  v13 = v4[3];
  if ( v13 >= 0x10 )
  {
    v14 = v13 + 1;
    v15 = *v4;
    if ( v14 > 0xFFFFFFFFFFFFFFFFui64 )
      invalid_parameter_noinfo_noreturn();
    if ( v14 >= 0x1000 )
    {
      if ( v15 & 0x1F )
        invalid_parameter_noinfo_noreturn();
      v16 = *(v15 - 1);
      if ( v16 >= v15 )
        invalid_parameter_noinfo_noreturn();
      v17 = v15 - v16;
      if ( v17 < 8 )
        invalid_parameter_noinfo_noreturn();
      if ( v17 > 0x27 )
        invalid_parameter_noinfo_noreturn();
      v15 = v16;
    }
    j_free(v15);
  }
  v4[3] = 15;
  v4[2] = 0i64;
  if ( v4[3] < 0x10 )
    result = v4;
  else
    result = *v4;
  *result = 0;
  *v4 = v9;
  v4[3] = v5;
  v4[2] = v3;
  if ( v4[3] >= 0x10 )
    v4 = v9;
  *(v4 + v3) = 0;
  return result;
}
// 1800048CD: using guessed type __int64 sub_1800048CD(void);
// 180005138: using guessed type void std::_Xbad_alloc(void);

//----- (00000001800034B0) ----------------------------------------------------
_QWORD *__fastcall sub_1800034B0(_QWORD *a1, __int64 a2)
{
  _QWORD *v2; // rbx
  __int64 v3; // rax
  _QWORD *v4; // rdx

  v2 = a1;
  v3 = a2;
  v4 = a1 + 1;
  *a1 = &std::exception::`vftable';
  *v4 = 0i64;
  v4[1] = 0i64;
  __std_exception_copy(v3 + 8);
  *v2 = &std::bad_cast::`vftable';
  return v2;
}
// 1800051B8: using guessed type __int64 __fastcall __std_exception_copy(_QWORD);
// 1800053B0: using guessed type void *std::exception::`vftable';
// 180005690: using guessed type void *std::bad_cast::`vftable';

//----- (00000001800034F0) ----------------------------------------------------
__int64 __fastcall sub_1800034F0(__int64 **a1)
{
  __int64 **v1; // rbx
  __int64 result; // rax
  __int64 v3; // rcx

  v1 = a1;
  if ( !std::uncaught_exception() )
    std::basic_ostream<char,std::char_traits<char>>::_Osfx(*v1);
  result = **v1;
  v3 = *(*v1 + *(result + 4) + 72);
  if ( v3 )
    result = (*(*v3 + 16i64))();
  return result;
}
// 1800050E8: using guessed type __int64 __fastcall std::basic_ostream<char,std::char_traits<char>>::_Osfx(_QWORD);
// 180005160: using guessed type bool std::uncaught_exception(void);

//----- (0000000180003540) ----------------------------------------------------
__int64 __fastcall sub_180003540(__int64 **a1)
{
  __int64 result; // rax
  __int64 v2; // rcx

  result = **a1;
  v2 = *(*a1 + *(result + 4) + 72);
  if ( v2 )
    result = (*(*v2 + 16i64))();
  return result;
}

//----- (0000000180003574) ----------------------------------------------------
char *__fastcall sub_180003574(__int64 a1, char a2)
{
  return sub_1800029A0(a1 - *(a1 - 4), a2);
}

//----- (00000001800035F0) ----------------------------------------------------
_QWORD *__fastcall sub_1800035F0(_QWORD *a1, char a2)
{
  _QWORD *v2; // rbx

  v2 = a1;
  *a1 = &type_info::`vftable';
  if ( a2 & 1 )
    j_j_free(a1);
  return v2;
}
// 180005388: using guessed type void *type_info::`vftable';

//----- (0000000180003B4C) ----------------------------------------------------
_QWORD *__fastcall sub_180003B4C(_QWORD *a1, __int64 a2)
{
  _QWORD *v2; // rbx
  __int64 v3; // rax
  _QWORD *v4; // rdx

  v2 = a1;
  v3 = a2;
  *a1 = &std::exception::`vftable';
  v4 = a1 + 1;
  *v4 = 0i64;
  v4[1] = 0i64;
  _std_exception_copy(v3 + 8);
  *v2 = &std::bad_alloc::`vftable';
  return v2;
}
// 180004602: using guessed type __int64 __fastcall _std_exception_copy(_QWORD);
// 1800053B0: using guessed type void *std::exception::`vftable';
// 1800053C8: using guessed type void *std::bad_alloc::`vftable';

//----- (0000000180003B8C) ----------------------------------------------------
_QWORD *__fastcall sub_180003B8C(_QWORD *a1)
{
  a1[2] = 0i64;
  a1[1] = "bad allocation";
  *a1 = &std::bad_alloc::`vftable';
  return a1;
}
// 1800053C8: using guessed type void *std::bad_alloc::`vftable';

//----- (0000000180003BAC) ----------------------------------------------------
_QWORD *__fastcall sub_180003BAC(_QWORD *a1, __int64 a2)
{
  _QWORD *v2; // rbx
  __int64 v3; // rax
  _QWORD *v4; // rdx

  v2 = a1;
  v3 = a2;
  *a1 = &std::exception::`vftable';
  v4 = a1 + 1;
  *v4 = 0i64;
  v4[1] = 0i64;
  _std_exception_copy(v3 + 8);
  *v2 = &std::bad_array_new_length::`vftable';
  return v2;
}
// 180004602: using guessed type __int64 __fastcall _std_exception_copy(_QWORD);
// 1800053B0: using guessed type void *std::exception::`vftable';
// 1800053F0: using guessed type void *std::bad_array_new_length::`vftable';

//----- (0000000180003BEC) ----------------------------------------------------
_QWORD *__fastcall sub_180003BEC(_QWORD *a1)
{
  a1[2] = 0i64;
  a1[1] = "bad array new length";
  *a1 = &std::bad_array_new_length::`vftable';
  return a1;
}
// 1800053F0: using guessed type void *std::bad_array_new_length::`vftable';

//----- (0000000180004118) ----------------------------------------------------
void sub_180004118()
{
  InitializeSListHead(&unk_1800088E0);
}

//----- (0000000180004128) ----------------------------------------------------
void __cdecl sub_180004128()
{
  _std_type_info_destroy_list(&unk_1800088E0);
}
// 180004620: using guessed type __int64 __fastcall _std_type_info_destroy_list(_QWORD);

//----- (0000000180004134) ----------------------------------------------------
void *sub_180004134()
{
  return &unk_1800088F0;
}

//----- (0000000180004158) ----------------------------------------------------
void *sub_180004158()
{
  return &unk_180008960;
}

//----- (00000001800042A8) ----------------------------------------------------
__int64 sub_1800042A8()
{
  _QWORD *i; // rbx
  __int64 result; // rax

  for ( i = &unk_180006438; i < &unk_180006438; ++i )
  {
    if ( *i )
      result = (*i)(*i);
  }
  return result;
}

//----- (00000001800042F4) ----------------------------------------------------
void __cdecl sub_1800042F4()
{
  _QWORD *i; // rbx

  for ( i = &unk_180006448; i < &unk_180006448; ++i )
  {
    if ( *i )
      (*i)(*i);
  }
}

//----- (0000000180004680) ----------------------------------------------------
char sub_180004680()
{
  return 1;
}

//----- (0000000180004684) ----------------------------------------------------
__int64 sub_180004684()
{
  return 0i64;
}

//----- (00000001800048CD) ----------------------------------------------------
#error "1800048EC: positive sp value has been found (funcsize=7)"

//----- (00000001800048FD) ----------------------------------------------------
void __usercall sub_1800048FD(__int64 a1@<rbp>)
{
  __int64 *v1; // rbx
  __int64 v2; // rax
  unsigned __int64 v3; // rax
  __int64 v4; // rcx

  v1 = *(a1 + 96);
  v2 = v1[3];
  JUMPOUT(v2, 16i64, &loc_180004967);
  v3 = v2 + 1;
  v4 = *v1;
  if ( v3 > 0xFFFFFFFFFFFFFFFFui64 )
    invalid_parameter_noinfo_noreturn();
  JUMPOUT(v3, 4096i64, &loc_180004962);
  JUMPOUT(v4 & 0x1F, 0, &loc_180004932);
  invalid_parameter_noinfo_noreturn();
}

//----- (00000001800049D2) ----------------------------------------------------
#error "1800049DD: positive sp value has been found (funcsize=0)"

#error "There were 2 decompilation failure(s) on 63 function(s)"
